//! The GRUB environment block (`grubenv`) -- a small, fixed-size key/
//! value store real grub2 (`grub-editenv`) uses for `saved_entry` (the
//! default boot entry to select) and boot-counting variables
//! (`boot_success`, `boot_indeterminate_count`), and the same file
//! `ociboot`'s own planned boot-counting/rollback logic (milestone 6)
//! will read and write.
//!
//! There is no single canonical written spec for this format (unlike
//! BLS entries, which the uapi-group does publish); grub2's own C
//! implementation is the only real authority, so every detail below
//! was verified directly against the real `grub-editenv` binary
//! (installed on this development host as part of `grub2-common`) by
//! side-by-side comparison, not assumed or guessed:
//!
//! - a fixed 94-byte header, byte-for-byte: `"# GRUB Environment
//!   Block\n# WARNING: Do not edit this file by tools other than
//!   grub-editenv!!!\n"` ([`HEADER`]).
//! - `grub-editenv create`'s own default total file size is exactly
//!   1024 bytes ([`DEFAULT_SIZE`]); real installs virtually always use
//!   that, though the real tool honors whatever size an *existing*
//!   file already is when updating it, never re-padding it back up to
//!   1024 -- confirmed by shrinking a real file below 1024 bytes by
//!   hand and updating it with the real tool, which left it exactly
//!   as short as before.
//! - after the header: `key=value\n` lines, in insertion order.
//!   Updating an *existing* key's value preserves its original
//!   position; a *new* key is appended after the last existing one;
//!   `unset` removes the line and shifts everything after it up --
//!   all confirmed directly against the real tool's own `set`/`unset`/
//!   `list` output, not assumed.
//! - the remainder of the file, after the last `key=value\n` line, is
//!   padding of literal `#` bytes up to the block's own total size.
//! - the real tool's own `set`/`unset` refuses to write (`"error:
//!   environment block too small"`) if the header plus every
//!   `key=value\n` line would not fit in the block's current total
//!   size -- confirmed directly, and matched here by
//!   [`GrubEnv::to_bytes`] returning an `Err` in the same situation
//!   rather than silently growing the file (a grubenv's own fixed
//!   size is deliberate: real GRUB reads it directly off disk at a
//!   known offset before a full filesystem driver is even available,
//!   during early boot, so it can never just grow arbitrarily).
//! - **not** replicated here: the real tool's own tolerance for
//!   genuinely malformed/adversarial content after the header (e.g. a
//!   stray non-`key=value` line embedded *before* a later real entry
//!   still gets echoed back by the real tool's own `list`, in a way
//!   that doesn't reduce to any single simple, obviously-intentional
//!   rule after extensive direct testing). A real grubenv file --
//!   whether written by the real `grub-editenv` or by this module --
//!   never contains such content in the first place: the header is
//!   always immediately followed by zero or more well-formed
//!   `key=value\n` lines and then, immediately, the `#` padding run,
//!   with no other shape possible. [`parse`] matches that real,
//!   well-formed shape byte-for-byte (confirmed via direct comparison
//!   against files the real tool itself produced) and simply stops at
//!   the first line that doesn't parse as `key=value`, exactly the
//!   boundary a well-formed file's own padding run creates.
//!
//! One deliberate improvement over the real tool, not just a port of
//! it: real `grub-editenv` writes in place (`open(O_WRONLY|O_CREAT|
//! O_TRUNC)`, confirmed directly via `strace`) with no atomicity at
//! all -- a power loss or crash mid-write can leave a real, booted
//! system's own grubenv truncated or corrupted. [`write`] instead
//! writes to a temporary file in the same directory and renames it
//! into place, so a caller only ever observes the old or the new
//! content, never a torn write -- a meaningful safety improvement for
//! a file that gates which OS deployment a real machine boots into
//! next.

use std::io::{self, Write as _};
use std::path::Path;

/// The fixed, literal grubenv header -- see this module's own doc
/// comment for how this was confirmed byte-for-byte against the real
/// `grub-editenv` binary.
pub const HEADER: &[u8] =
    b"# GRUB Environment Block\n# WARNING: Do not edit this file by tools other than grub-editenv!!!\n";

/// `grub-editenv create`'s own default total block size.
pub const DEFAULT_SIZE: usize = 1024;

/// A parsed (or freshly created) grubenv block: an ordered list of
/// `key=value` entries plus the total on-disk size the block must
/// serialize back to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GrubEnv {
    entries: Vec<(String, String)>,
    size: usize,
}

impl Default for GrubEnv {
    fn default() -> Self {
        Self::new()
    }
}

impl GrubEnv {
    /// A fresh, empty environment block at the real tool's own
    /// default size (`grub-editenv create`'s own 1024 bytes).
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
            size: DEFAULT_SIZE,
        }
    }

    /// The value currently set for `key`, if any.
    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
    }

    /// Every `(key, value)` pair currently set, in the same order
    /// they'd be written back out (`ociboot grubenv list`'s own
    /// backing — matches real `grub-editenv list`'s own insertion-
    /// order output).
    pub fn entries(&self) -> impl Iterator<Item = (&str, &str)> {
        self.entries.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    /// Set `key` to `value`. If `key` already exists, its value is
    /// replaced *in place* (its original position among the other
    /// entries is preserved); otherwise it's appended after the last
    /// existing entry -- both confirmed directly against the real
    /// tool's own behavior, not assumed.
    ///
    /// Doesn't itself fail if the result would no longer fit in this
    /// block's own total size -- exactly like the real tool, that
    /// check only happens once, at serialization time
    /// ([`to_bytes`](Self::to_bytes)/[`write`]), not per individual
    /// mutation.
    pub fn set(&mut self, key: &str, value: &str) {
        if let Some(entry) = self.entries.iter_mut().find(|(k, _)| k == key) {
            entry.1 = value.to_string();
        } else {
            self.entries.push((key.to_string(), value.to_string()));
        }
    }

    /// Remove `key` if present; a no-op if it isn't.
    pub fn unset(&mut self, key: &str) {
        self.entries.retain(|(k, _)| k != key);
    }

    /// Serialize back to this block's own total size: the fixed
    /// [`HEADER`], then every entry as a `key=value\n` line in order,
    /// then `#` padding filling the rest.
    ///
    /// Returns an `io::ErrorKind::InvalidInput` error -- matching the
    /// real tool's own `"environment block too small"` -- if the
    /// header plus every entry line wouldn't fit in this block's own
    /// size.
    pub fn to_bytes(&self) -> io::Result<Vec<u8>> {
        let mut body = String::new();
        for (key, value) in &self.entries {
            body.push_str(key);
            body.push('=');
            body.push_str(value);
            body.push('\n');
        }
        if HEADER.len() + body.len() > self.size {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "environment block too small",
            ));
        }
        let mut out = Vec::with_capacity(self.size);
        out.extend_from_slice(HEADER);
        out.extend_from_slice(body.as_bytes());
        out.resize(self.size, b'#');
        Ok(out)
    }
}

/// Parse a grubenv block's raw bytes, as read from a real file.
///
/// Returns an `io::ErrorKind::InvalidData` error -- matching the real
/// tool's own `"invalid environment block"` -- if `data` is shorter
/// than [`HEADER`] or doesn't start with it exactly.
pub fn parse(data: &[u8]) -> io::Result<GrubEnv> {
    if data.len() < HEADER.len() || &data[..HEADER.len()] != HEADER {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "invalid grubenv: missing or mismatched header",
        ));
    }
    let size = data.len();
    let body = &data[HEADER.len()..];

    let mut entries = Vec::new();
    for line in body.split(|&b| b == b'\n') {
        let Ok(text) = std::str::from_utf8(line) else {
            break;
        };
        let Some(eq) = text.find('=') else {
            break;
        };
        entries.push((text[..eq].to_string(), text[eq + 1..].to_string()));
    }
    Ok(GrubEnv { entries, size })
}

/// Read and parse a grubenv file.
pub fn read(path: &Path) -> io::Result<GrubEnv> {
    parse(&std::fs::read(path)?)
}

/// Write `env` to `path`, atomically (a real, deliberate improvement
/// over the real `grub-editenv` binary's own in-place, non-atomic
/// write -- see this module's own top doc comment).
pub fn write(path: &Path, env: &GrubEnv) -> io::Result<()> {
    let bytes = env.to_bytes()?;
    let dir = path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let mut tmp = tempfile::NamedTempFile::new_in(dir)?;
    tmp.write_all(&bytes)?;
    tmp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    /// The real binary is called `grub-editenv` on Debian/Ubuntu
    /// (`grub-common`) but `grub2-editenv` on Fedora/CentOS Stream
    /// (`grub2-tools`) -- confirmed directly, not assumed: the two
    /// distro families never shipped a common alias for it. Every
    /// test that compares against the real tool tries both and skips
    /// itself with a clear message if neither is installed, matching
    /// this workspace's existing pattern for tool-dependent tests
    /// (`oci-erofs::builder`/`oci-erofs::dmverity`). Needs no
    /// privilege at all: the real tool operates on a plain file given
    /// any path, confirmed directly.
    fn grub_editenv_binary() -> Option<&'static str> {
        ["grub-editenv", "grub2-editenv"].into_iter().find(|name| {
            Command::new(name)
                .arg("--version")
                .output()
                .is_ok_and(|out| out.status.success())
        })
    }

    #[test]
    fn a_fresh_grubenv_round_trips_through_the_real_grub_editenv() {
        let Some(bin) = grub_editenv_binary() else {
            eprintln!("skipping: neither grub-editenv nor grub2-editenv is installed");
            return;
        };
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("grubenv");

        let mut env = GrubEnv::new();
        env.set("saved_entry", "0");
        env.set("boot_success", "1");
        write(&path, &env).unwrap();

        let out = Command::new(bin).arg(&path).arg("list").output().unwrap();
        assert!(
            out.status.success(),
            "real {bin} should accept a file this module wrote"
        );
        let listed = String::from_utf8_lossy(&out.stdout);
        assert!(listed.contains("saved_entry=0"));
        assert!(listed.contains("boot_success=1"));
    }

    #[test]
    fn a_file_created_by_the_real_grub_editenv_round_trips_here() {
        let Some(bin) = grub_editenv_binary() else {
            eprintln!("skipping: neither grub-editenv nor grub2-editenv is installed");
            return;
        };
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("grubenv");

        assert!(
            Command::new(bin)
                .arg(&path)
                .arg("create")
                .status()
                .unwrap()
                .success()
        );
        assert!(
            Command::new(bin)
                .arg(&path)
                .arg("set")
                .arg("boot_success=1")
                .arg("boot_indeterminate_count=0")
                .status()
                .unwrap()
                .success()
        );

        let env = read(&path).unwrap();
        assert_eq!(env.get("boot_success"), Some("1"));
        assert_eq!(env.get("boot_indeterminate_count"), Some("0"));

        // Round-trip: writing it back out here must reproduce exactly
        // what the real tool itself would have on disk.
        let raw = std::fs::read(&path).unwrap();
        assert_eq!(env.to_bytes().unwrap(), raw);
    }

    #[test]
    fn set_on_an_existing_key_preserves_its_position_matching_the_real_tool() {
        let Some(bin) = grub_editenv_binary() else {
            eprintln!("skipping: neither grub-editenv nor grub2-editenv is installed");
            return;
        };
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("grubenv");
        assert!(
            Command::new(bin)
                .arg(&path)
                .arg("create")
                .status()
                .unwrap()
                .success()
        );
        assert!(
            Command::new(bin)
                .arg(&path)
                .arg("set")
                .arg("a=1")
                .arg("b=2")
                .status()
                .unwrap()
                .success()
        );

        let mut env = read(&path).unwrap();
        env.set("a", "99");
        write(&path, &env).unwrap();

        let out = Command::new(bin).arg(&path).arg("list").output().unwrap();
        let listed = String::from_utf8_lossy(&out.stdout);
        let lines: Vec<&str> = listed.lines().collect();
        assert_eq!(
            lines,
            vec!["a=99", "b=2"],
            "updating 'a' must not reorder 'b'"
        );
    }

    #[test]
    fn unset_removes_the_entry_and_a_new_key_is_appended_at_the_end() {
        let mut env = GrubEnv::new();
        env.set("a", "1");
        env.set("b", "2");
        env.unset("a");
        env.set("c", "3");
        assert_eq!(env.get("a"), None);
        assert_eq!(env.get("b"), Some("2"));
        assert_eq!(env.get("c"), Some("3"));

        let bytes = env.to_bytes().unwrap();
        let reparsed = parse(&bytes).unwrap();
        assert_eq!(
            reparsed.entries,
            vec![
                ("b".to_string(), "2".to_string()),
                ("c".to_string(), "3".to_string())
            ]
        );
    }

    #[test]
    fn to_bytes_matches_the_real_headers_own_94_bytes() {
        let env = GrubEnv::new();
        let bytes = env.to_bytes().unwrap();
        assert_eq!(bytes.len(), DEFAULT_SIZE);
        assert_eq!(&bytes[..HEADER.len()], HEADER);
        assert!(bytes[HEADER.len()..].iter().all(|&b| b == b'#'));
    }

    #[test]
    fn to_bytes_refuses_to_overflow_the_blocks_own_size() {
        let mut env = GrubEnv::new();
        env.set("long", &"x".repeat(2000));
        let err = env.to_bytes().unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidInput);
    }

    #[test]
    fn parse_rejects_a_missing_or_wrong_header() {
        assert!(parse(b"not a grubenv").is_err());
        assert!(parse(b"").is_err());
        let mut wrong = HEADER.to_vec();
        wrong[2] = b'X';
        assert!(parse(&wrong).is_err());
    }

    #[test]
    fn parse_accepts_a_header_only_block_with_no_entries() {
        let env = parse(HEADER).unwrap();
        assert!(env.get("anything").is_none());
        assert_eq!(env.to_bytes().unwrap(), HEADER);
    }

    #[test]
    fn write_is_atomic_leaving_old_content_intact_on_a_too_small_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("grubenv");

        let mut original = GrubEnv::new();
        original.set("safe", "value");
        write(&path, &original).unwrap();
        let before = std::fs::read(&path).unwrap();

        // Force `to_bytes` to fail without ever calling `write` with
        // it -- `write` itself should never be reached with bad
        // content, but this also documents that a failing `to_bytes`
        // never touches the file at all.
        let mut too_big = GrubEnv::new();
        too_big.set("long", &"x".repeat(2000));
        assert!(too_big.to_bytes().is_err());

        let after = std::fs::read(&path).unwrap();
        assert_eq!(
            before, after,
            "a failed serialization must never touch the real file"
        );
    }

    #[test]
    fn value_containing_an_equals_sign_round_trips() {
        let mut env = GrubEnv::new();
        env.set("options", "root=UUID=abc-123 rw quiet");
        let bytes = env.to_bytes().unwrap();
        let reparsed = parse(&bytes).unwrap();
        assert_eq!(reparsed.get("options"), Some("root=UUID=abc-123 rw quiet"));
    }
}
