//! RFC 3339 UTC timestamp formatting, without a date/time dependency.
//!
//! Originally written for `oci_runtime_core::PersistedState::created`
//! (a `YYYY-MM-DDTHH:MM:SSZ` string for `SystemTime::now()`); moved
//! here so [`image::ImageConfig::created`](crate::image::ImageConfig)
//! and [`image::HistoryEntry::created`](crate::image::HistoryEntry) —
//! both defined in this same crate — can format a real timestamp for
//! themselves too (`oci_dockerfile::commit_layer`'s own future caller
//! needs exactly this), without either duplicating the same hand-
//! rolled math a second time or making `oci-dockerfile` depend on
//! `oci-runtime-core` just for a date string. Pulling in `chrono`/
//! `time` for this one conversion would also be a lot of dependency
//! weight (and a new "date/time" capability group `ci/guards.py`
//! would have to start policing), so this hand-rolls the civil-
//! calendar math instead: Howard Hinnant's `civil_from_days` algorithm
//! (public domain; see
//! <http://howardhinnant.github.io/date_algorithms.html#civil_from_days>),
//! which is a small, well-known, exhaustively-tested-elsewhere formula for
//! days-since-epoch -> (year, month, day) and back.

use std::time::SystemTime;

/// Format `time` as `YYYY-MM-DDTHH:MM:SSZ` (UTC, second precision — the
/// same precision `runc`'s `state.json` uses in practice). Times before
/// the Unix epoch format as the epoch itself (state timestamps are always
/// `SystemTime::now()`, never user input).
pub fn format_rfc3339_utc(time: SystemTime) -> String {
    let secs = time
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);

    let days = secs.div_euclid(86_400);
    let time_of_day = secs.rem_euclid(86_400);
    let (hour, minute, second) = (
        time_of_day / 3600,
        (time_of_day / 60) % 60,
        time_of_day % 60,
    );
    let (year, month, day) = civil_from_days(days);

    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

/// Days-since-1970-01-01 -> (year, month, day). See module docs for the
/// source algorithm.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365; // [0, 399]
    let year = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let year = if month <= 2 { year + 1 } else { year };
    (year, month, day)
}

/// The exact inverse of [`format_rfc3339_utc`]: parses a
/// `YYYY-MM-DDTHH:MM:SSZ` string back into a [`SystemTime`]. Only ever
/// needs to handle that one fixed shape (this project's own
/// `PersistedState::created`/`ImageConfig::created`/etc. are always
/// generated by `format_rfc3339_utc` itself, never arbitrary user
/// input) — anything else, including a fractional-second or
/// explicit-offset RFC 3339 timestamp a *different* real tool might
/// produce, is `None` rather than guessed at. `days_from_civil` is
/// Howard Hinnant's own published inverse of `civil_from_days` (same
/// source as the module doc comment).
pub fn parse_rfc3339_utc(s: &str) -> Option<SystemTime> {
    let bytes = s.as_bytes();
    if bytes.len() != 20
        || bytes[4] != b'-'
        || bytes[7] != b'-'
        || bytes[10] != b'T'
        || bytes[13] != b':'
        || bytes[16] != b':'
        || bytes[19] != b'Z'
    {
        return None;
    }
    let digits = |range: std::ops::Range<usize>| -> Option<i64> { s.get(range)?.parse().ok() };
    let year = digits(0..4)?;
    let month = digits(5..7)?;
    let day = digits(8..10)?;
    let hour = digits(11..13)?;
    let minute = digits(14..16)?;
    let second = digits(17..19)?;
    if !(1..=12).contains(&month) || !(1..=31).contains(&day) {
        return None;
    }
    if hour > 23 || minute > 59 || second > 59 {
        return None;
    }
    let days = days_from_civil(year, month as u32, day as u32);
    let secs = days * 86_400 + hour * 3600 + minute * 60 + second;
    if secs < 0 {
        return None;
    }
    Some(std::time::UNIX_EPOCH + std::time::Duration::from_secs(secs as u64))
}

/// (year, month, day) -> days-since-1970-01-01. See module docs for the
/// source algorithm (the published inverse of [`civil_from_days`]).
fn days_from_civil(year: i64, month: u32, day: u32) -> i64 {
    let y = if month <= 2 { year - 1 } else { year };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = (y - era * 400) as u64; // [0, 399]
    let mp = if month > 2 { month - 3 } else { month + 9 }; // [0, 11]
    let doy = (153 * mp as u64 + 2) / 5 + day as u64 - 1; // [0, 365]
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy; // [0, 146096]
    era * 146_097 + doe as i64 - 719_468
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    #[test]
    fn epoch_formats_correctly() {
        assert_eq!(
            format_rfc3339_utc(std::time::UNIX_EPOCH),
            "1970-01-01T00:00:00Z"
        );
    }

    #[test]
    fn known_timestamp_formats_correctly() {
        // 1705329296 = 2024-01-15T14:34:56Z, cross-checked with
        // `date -u -d @1705329296 +%Y-%m-%dT%H:%M:%SZ`.
        let t = std::time::UNIX_EPOCH + Duration::from_secs(1_705_329_296);
        assert_eq!(format_rfc3339_utc(t), "2024-01-15T14:34:56Z");
    }

    #[test]
    fn leap_day_formats_correctly() {
        // 2024-02-29T00:00:00Z = 1709164800
        let t = std::time::UNIX_EPOCH + Duration::from_secs(1_709_164_800);
        assert_eq!(format_rfc3339_utc(t), "2024-02-29T00:00:00Z");
    }

    #[test]
    fn end_of_year_formats_correctly() {
        // 1999-12-31T23:59:59Z = 946684799
        let t = std::time::UNIX_EPOCH + Duration::from_secs(946_684_799);
        assert_eq!(format_rfc3339_utc(t), "1999-12-31T23:59:59Z");
    }

    #[test]
    fn parse_is_the_exact_inverse_of_format_across_a_wide_range() {
        for secs in [
            0,
            1,
            946_684_799,   // 1999-12-31T23:59:59Z
            1_705_329_296, // 2024-01-15T14:34:56Z
            1_709_164_800, // 2024-02-29T00:00:00Z (leap day)
            1_800_000_000,
            4_000_000_000, // well past 2100
        ] {
            let t = std::time::UNIX_EPOCH + Duration::from_secs(secs);
            let formatted = format_rfc3339_utc(t);
            assert_eq!(
                parse_rfc3339_utc(&formatted),
                Some(t),
                "round trip of {formatted}"
            );
        }
    }

    #[test]
    fn parse_rejects_anything_not_shaped_exactly_like_format_rfc3339_utcs_own_output() {
        assert_eq!(parse_rfc3339_utc(""), None);
        assert_eq!(parse_rfc3339_utc("garbage"), None);
        // A fractional-second/explicit-offset RFC 3339 timestamp a
        // different real tool might produce -- deliberately not
        // guessed at, see this function's own doc comment.
        assert_eq!(parse_rfc3339_utc("2024-01-15T14:34:56.123Z"), None);
        assert_eq!(parse_rfc3339_utc("2024-01-15T14:34:56+01:00"), None);
        // Wrong separators in an otherwise correctly-sized string.
        assert_eq!(parse_rfc3339_utc("2024-01-15X14:34:56Z"), None);
        // Out-of-range components.
        assert_eq!(parse_rfc3339_utc("2024-13-15T14:34:56Z"), None);
        assert_eq!(parse_rfc3339_utc("2024-01-15T25:34:56Z"), None);
    }
}
